Fix AttributeError introduced by paramiko update.
Fixed AttributeError: 'property' object has no attribute 'update'.  The `_handler_table` is no longer a dictionary, though `_client_handler_table` is.  The fix simply uses `_client_handler_table` instead of `_handler_table`.  The same information needed for the exploit is available in both.